# This is a separate run of the Python test suite that doesn't cache the tox
# environment and runs from a schedule.  The purpose is to test compatibility
# with the latest versions of dependencies.

name: Periodic CI

'on':
  schedule:
    - cron: '0 12 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - '3.11'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Run tests in tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: 'lint,typing,py'
          use-cache: false

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docs in tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: '3.11'
          tox-envs: 'demo,docs,docs-linkcheck'
          use-cache: false

  test-packaging:
    name: Test packaging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Build and publish
        uses: lsst-sqre/build-and-publish-to-pypi@v2
        with:
          python-version: '3.11'
          upload: false
